os:
  - Visual Studio 2017

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      QT5: C:\Qt\5.11\msvc2017_64

build:
  verbosity: detailed

configuration:
  - Release


before_build:
  - set Path=%QT5%\bin;%Path%
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%" "-DCMAKE_BUILD_TYPE=Release"

build_script:
  - cd build
  - cmake --build .
  - cd Debug
  - windeployqt harlequin.exe --debug
  - 7z a -t7z harlequin.7z *

artifacts:
  - path: build/Debug/harlequin.7z

deploy:
  provider: GitHub
  auth_token:
    secure: kTvOSw2ee+EuRoUK5bphhcG1cV6Ls/rCCGyJyNf7Ndo7FQiJWBzzwM3Eyj5dpSlI
  artifact: /.*\.7z/
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
