os:
  - Visual Studio 2017

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      QT5: C:\Qt\5.11\msvc2017_64

build:
  verbosity: detailed

configuration:
  - Release


before_build:
  - set Path=%QT5%\bin;%Path%
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%QT5%"

build_script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release .. 
  - cmake --build .
